#!/bin/bash

CURRENT="$(mpc -h entoma current)"
if [[ -z $CURRENT ]];
then
	CURRENT="$(echo -e "\uf025") Nothing playing"
else
	CURRENT="$(echo -e "\uf025") $CURRENT"
fi
twmnc -t "Currently Playing" -c "$CURRENT" --id 3
