#!/bin/zsh

sudo rsync -aAX --info=progress2 --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/run/media/*","/home/*/.cache/*","/home/*/.thumbnails/*","/home/*/.local/share/Trash/*","/home/*/.gvfs"} / /run/media/jerry/WD750/ArchBackup
