#!/bin/zsh

bspc config focused_border_color \#20b2aa

nitrogen --head=0 --set-zoom-fill ~/Pictures/day.jpg
nitrogen --head=1 --set-zoom-fill ~/.config/bspwm/Space-Desktop.jpg

xrdb -merge ~/.Xresources

light -S 100
