#!/bin/bash

# Close applications
if pgrep "panel_bar" > /dev/null
then
	pkill panel &
fi
if pgrep "chromium" > /dev/null
then
	pkill chromium &
fi
if pgrep "firefox" > /dev/null
then
	pkill firefox &
fi
if pgrep "libreoffice" > /dev/null
then
	pkill libreoffice &
fi

# Logout of XFCE4
if pgrep "xfce4" > /dev/null
then
	#Tested: Working
	xfce4-session-logout --logout --fast &
fi

# Logout of GNOME
if pgrep "gnome" > /dev/null
then
	# Untested
	# I don't actually use GNOME
	gnome-session-quit &
fi

# Logout of KDE
if pgrep "kde" > /dev/null
then
	# Untested
	# I don't know which one works so I'll just put both here
	# I don't actually use KDE Plasma 5
	qdbus org.kde.ksmserver /KSMServer logout 0 3 3 &
	loginctl terminate-user "jerry" &
fi

# Logout of bpswm
if pgrep "bspwm" > /dev/null
then
	# Tested: Working
	bspc quit &
fi

# Logout of i3
if pgrep "i3" > /dev/null
then
	# Untested
	i3 exit &
fi

# Log out of tmux
if pgrep "tmux" > /dev/null
then
	# Tested: Working
	tmux kill-session &
fi
exit
