#!/bin/bash

xwobf /tmp/screen.png
convert /tmp/screen.png ~/Scripts/lock.png -gravity center -composite -matte /tmp/screen.png
pkill compton
i3lock -u -i /tmp/screen.png
rm /tmp/screen.png
while pgrep "i3lock" >> /dev/null
do
	sleep 0.05
done
compton &!
