#!/bin/bash

echo "New structure:"
git remote set-url origin git@git.geraldwu.com:98WuG/$1
git remote set-url origin --add git@github.com:98WuG/$1
git remote add origin-github git@github.com:98WuG/$1
git remote -v
echo "Done"
echo "Run \`git push\` when ready"
