#!/bin/bash

if [ -z "$1" ];
then
	REPO="$(pwd | rev | cut -d'/' -f1 | rev)"
	echo -e "No argument provided!\nDefaulting to current directory name ($REPO)..."
	read -r -p "Is this okay? [y/N] " response
	case "$response" in
		[yY][eE][sS]|[yY])
			;;
		*)
			echo "Please re-run as \`migrate \$repo-name\`"
			exit 1
			;;
	esac
else
	REPO="$@"
fi

git remote set-url origin git@git.geraldwu.com:98WuG/$REPO
git remote set-url origin --add git@github.com:98WuG/$REPO
git remote add origin-github git@github.com:98WuG/$REPO

echo -e "\nNew structure:"
git remote -v
echo ""

read -r -p "Push to all remotes? [y/N] " response
case "$response" in
	[yY][eE][sS]|[yY])
		git push
		;;
	*)
		echo "Run \`git push\` to push changes when ready"
		;;
esac
