#!/bin/zsh

CURRENT="$(mpc current | sed -r 's/&/&amp;/g')"
if [[ -z $CURRENT ]];
then
	CURRENT="$(echo -e "\uf025") Nothing playing"
else
	CURRENT="$(echo -e "\uf025") $CURRENT"
fi
notify-send "Currently Playing" "$CURRENT"
