#!/bin/sh

CURRENT="$(mpc current | sed -r 's/&/&amp;/g')"
if [[ -z $CURRENT ]];
then
	CURRENT="$(echo -e "\uf001") Nothing playing"
else
	CURRENT="$(echo -e "\uf001") Now Playing: $CURRENT"
fi
echo $CURRENT
