#!/bin/zsh

pkill dunst && dunst &!
MUTESTATUS="$(pamixer --get-mute)"
if [ $MUTESTATUS = "false" ];
then
	notify-send "$(echo -e "\uf028") $(pamixer --get-volume)"
else
	notify-send "$(echo -e "\uf026") MUTE"
fi
