#!/bin/zsh

bspc config focused_border_color \#777777

nitrogen --head=0 --set-zoom-fill ~/Pictures/night.jpg
nitrogen --head=1 --set-zoom-fill ~/.config/bspwm/Space-Desktop.jpg

xrdb -merge ~/.Xresources_night

light -S 50
