#!/bin/bash

# I know this is inefficient af but I can't find a better way
if pgrep "panel_bar" > /dev/null
then
	# If running, hide (kill) it
	pkill panel_bar &
	bspc config top_padding 10
else
	# If it's not running, show (start) it
	panel & 2>> ~/logs/whomst
fi
