#!/bin/zsh

PS3='Please enter your choice: '
options=("Lock" "Logoff" "Shutdown" "Reboot" "Cancel")
echo -e "\e[4mPower Menu\e[0m"
select opt in "${options[@]}"
do
	case $opt in
		"Lock")
			~/Scripts/lock/lock &
			;;
		"Logoff")
			~/Scripts/exit &
			;;
		"Shutdown")
			shutdown now &
			;;
		"Reboot")
			reboot &
			;;
		"Cancel")
			break
			;;
		*) echo invalid option;;
	esac
done
