#!/bin/sh

if [ "$(xinput get-button-map 13)" = "1 2 3 4 5 6 7 " ];
then
	xinput set-button-map 13 1 2 3 5 4 6 7
	notify-send "Natural scrolling" "Enabled"
else
	xinput set-button-map 13 1 2 3 4 5 6 7
	notify-send "Natural scrolling" "Disabled"
fi
