#!/bin/zsh

STATUS=""

# Date status
DATE="$(echo -e "\uf073") $(date +%b) $(date +%d)"

# Time status
TIME="$(echo -e "\uf017") $(date +%I:%M%p)"


# Battery status
if [[ $(acpi) == *"Full"* ]];
then
	BATTERY="$(echo -e "\uf1e6 \uf240") FULL"
else
	if [[ $(acpi) == *"Unknown"* ]];
	then
		BATTERY="$(acpi | cut -d ' ' -f 4 | sed 's/.$//')"
	else
		BATTERY="$(acpi | cut -d ' ' -f 4 | sed 's/..$//')"
	fi
	if [ $BATTERY -gt 80 ];
	then
		BATTERY="$(echo -e "\uf240") $BATTERY%"
	elif [ $BATTERY -gt 60 ];
	then
		BATTERY="$(echo -e "\uf241") $BATTERY%"
	elif [ $BATTERY -gt 40 ];
	then
		BATTERY="$(echo -e "\uf242") $BATTERY%"
	elif [ $BATTERY -gt 20 ];
	then
		BATTERY="$(echo -e "\uf243") $BATTERY%"
	else
		BATTERY="$(echo -e "\uf244") $BATTERY%"
	fi
	if [[ $(acpi) != *"Discharging"* ]];
	then
		BATTERY="$(echo -e "\uf1e6") $BATTERY"
	fi
fi

# Network status
WIRELESS="$(echo -e "\uf1eb")"
if [ $(nmcli dev status | sed -n 2p | cut -d " " -f 11) != "--" ];
then
	WIRELESS="$WIRELESS $(nmcli dev status | sed -n 2p | cut -d " " -f 11 | tr '[:lower:]' '[:upper:]')"
else
	WIRELESS="$WIRELESS DISCONNECTED"
fi

# Music
CURRENT="$(mpc current | sed -r 's/&/&amp;/g')"
if [[ -z $CURRENT ]];
then
	CURRENT="$(echo -e "\uf025") Nothing playing"
else
	PLAYSTATUS="$(mpc | sed -n 2p | cut -d " " -f 1 | sed 's/.$//' | sed 's/^.//' | tr '[:lower:]' '[:upper:]')"
	POSITION="$(mpc | sed -n 2p | cut -d " " -f 6 | cut -d "/" -f 1)"
	CURRENT="$(echo -e "\uf025") $PLAYSTATUS: $CURRENT [$POSITION]"
fi

STATUS="$DATE $TIME $BATTERY $WIRELESS"
notify-send "$CURRENT" "$STATUS"
