#!/bin/bash

STATUS=""

# Date status
DATE="$(echo -e "\uf073") $(date +%b) $(date +%d)"

# Time status
TIME="$(echo -e "\uf017") $(date +%I:%M%p)"


# Battery status
if [[ $(acpi) == *"Full"* ]];
then
	BATTERY="$(echo -e "\uf1e6 \uf240") FULL"
else
	if [[ $(acpi) == *"Unknown"* ]];
	then
		BATTERY="$(acpi | cut -d ' ' -f 4 | sed 's/.$//')"
	else
		BATTERY="$(acpi | cut -d ' ' -f 4 | sed 's/..$//')"
	fi
	if [ $BATTERY -gt 80 ];
	then
		BATTERY="$(echo -e "\uf240") $BATTERY%"
	elif [ $BATTERY -gt 60 ];
	then
		BATTERY="$(echo -e "\uf241") $BATTERY%"
	elif [ $BATTERY -gt 40 ];
	then
		BATTERY="$(echo -e "\uf242") $BATTERY%"
	elif [ $BATTERY -gt 20 ];
	then
		BATTERY="$(echo -e "\uf243") $BATTERY%"
	else
		BATTERY="$(echo -e "\uf244") $BATTERY%"
	fi
	if [[ $(acpi) != *"Discharging"* ]];
	then
		BATTERY="$(echo -e "\uf1e6") $BATTERY"
	fi
fi

# Network status
WIRELESS="$(echo -e "\uf1eb")"
NETWORK="$(nmcli | sed -n 1p | grep "connected to" | sed 's/^.*to //g')"
echo $NETWORK
if [ -z "$NETWORK" ];
then
	WIRELESS="$WIRELESS DISCONNECTED"
else
	WIRELESS="$WIRELESS $NETWORK"
fi

# Volume
MUTESTATUS="$(pamixer --get-mute)"
if [ $MUTESTATUS = "false" ];
then
	VOLUME="$(echo -e "\uf028") $(pamixer --get-volume)"
else
	VOLUME="$(echo -e "\uf026") MUTE"
fi

# Brightness
BRIGHTNESS="$(echo -e "\uf185") $(light -G | sed 's/...$//')"

## Music
#CURRENT="$(mpc current | sed -r 's/&/&amp;/g')"
#if [[ -z $CURRENT ]];
#then
#	CURRENT="$(echo -e "\uf025") Nothing playing"
#else
#	PLAYSTATUS="$(mpc | sed -n 2p | cut -d " " -f 1 | sed 's/^.\(.*\).$/\1/' | tr '[:lower:]' '[:upper:]')"
#	POSITION="$(mpc | sed -n 2p | rev | cut -d " " -f 2 | rev )"
#	if [[ "$PLAYSTATUS" == "PLAYING" ]]; then
#		PLAYSTATUS="$(echo -e "\uf04b")"
#	else
#		PLAYSTATUS="$(echo -e "\uf04c")"
#	fi
#	CURRENT="$PLAYSTATUS  $CURRENT [$POSITION]"
#fi

STATUS="$DATE $TIME $BATTERY\n$WIRELESS $BRIGHTNESS $VOLUME"
notify-send "STATUS" "$STATUS"
