#!/bin/zsh

LAT=38.933868N
LONG=77.177260W

if pgrep -x "sunwait" > /dev/null
then
	notify-send "Sunwait already running"
else
	if [[ $(sunwait poll $LAT $LONG) == NIGHT ]];
	then
		~/Scripts/night
	fi
	while true
	do
		sunwait wait rise $LAT $LONG ; ~/Scripts/day
		sunwait wait set $LAT $LONG ; ~/Scripts/night
	done
fi
