#!/bin/bash

if [ -z "$@" ];
then
	echo "No arguments given"
	exit 1
else
	if xinput list | grep -q -i "$@";
	then
		if echo "$@" | grep -q -i "keyboard";
		then
			echo -e "Please think about your life choices\nDo not toggle the keyboard"
			exit 1
		else
			id=`xinput list | grep -i "$@" | sed 's/.*id\=\([0-9]\+\).*/\1/g'`

			declare -i status
			status=`xinput list-props ${id} | grep Device\ Enabled | sed -e 's/.*\:[ \t]\+//g'`

			if [ 0 -eq ${status} ];
			then
				xinput enable ${id}
				twmnc -t "$@" -c "$(echo -e "\uf00c") Enabled" --id 7
			else
				xinput disable ${id}
				twmnc -t "$@" -c "$(echo -e "\uf00d") Disabled" --id 7
			fi
		fi
	else
		echo "Device \"$@\" not found"
		exit 1
	fi
fi
