#!/bin/bash

pkill dunst && dunst &!

default=$(pacmd list-sinks | awk '/* index:/{print$3}')

if [ "$1" = "up" ];
then
	pactl set-sink-mute $default false
	pactl set-sink-volume $default +2%
elif [ "$1" = "down" ];
then
	pactl set-sink-mute $default false
	pactl set-sink-volume $default -2%
else
	pactl set-sink-mute $default toggle
	if [ "$(pamixer --get-mute)" = "true" ];
	then
		notify-send "$(echo -e "\uf026") MUTE"
	fi
fi

if [ "$(pamixer --get-mute)" = "false" ];
then
	VOLUME="$(echo -e "\uf028") $(pamixer --get-volume)"
	notify-send "$VOLUME"
fi
